version: "3.9"
services: 
  aem-cs:
    environment:
       - TZ=America/Montreal
       - NATIVE_SERVICE_HOST=aem-formsdocservice-native
    image: openjdk:11.0.10-jdk
    build:
      context: ./
      dockerfile: AEM.Dockerfile
    image: pat-lego.aem.dev:aem-cs
    volumes: 
      - ./.aem:/opt/adobe/aem
    restart: always
    ports:
      - "4502:4502"
      - "8000:8000"
  aem-formsdocservice-native:
    image: aem-ethos/formsdocservice-native-sdk:1.0.114
    volumes:
      - type: bind
        source: ${AEM_FONTS_DIR}
        target: /mnt/shared/fonts/adobe
      - type: bind
        source: ${AEM_LOGS_DIR}
        target: /logging/forms-docservices
    ports:
      - 8007:8007
      - 8008:8008
    environment:
      - REGION_NAME=local
      - ENVIRONMENT_NAME=local
      - SDK_TEMP_DIR=/opt/adobe/aem/crx-quickstart/temp
      - SHARED_TEMP_DIR=/mnt/shared/temp
    depends_on: 
        - aem-cs

